### ISSUE TITLE
Example of directly acquiring the frame without opening a GUI

### ISSUE THREAD

**Issue by xihuiwu** [danyu9394/linux_camera_tool#13]
Hello, I would like to whether I could directly store the camera frame to OpenCV mat for further processing without a GUI.

**Comment by danyu9394** [comment]
Yes you can, just follow the image processing pipeline in the code. Comment out the fork related part and go through everything in streaming_loop(). All the mat related ISP stuff I put them in src/isp_lib.cpp.
