### ISSUE TITLE
Is this Camera & version support software trigger?

### ISSUE THREAD

**Issue by trickyMan** [danyu9394/linux_camera_tool#3]
Camera Model: AR023ZWDR
Hardware Rev: 102
Firmware Rev:980

Is this camera support software trigger?

I found trigger_enable return error which is I/O error.

**Comment by trickyMan** [comment]
Fixed.

**Comment by danyu9394** [comment]
Triggering might not enable in the firmware if you get the error message. 
You can try to manually write to the sensor registers to enable trigger mode, 
search "AP0202_WRITE_REG_ON_THE_FLY" in the code. After running that, you will see streaming stop.
Then use a function generator supplying to the trigger pin, I forget the exact pin #, you can check with our datasheet/schematics. Voltage doesn't matter that much we got an optocoupler to get that covered. Then generate the trigger pulse. You will be able to see the streaming at the exact frame rate where you trigger at.
But I am not sure if that version of ISP binary support triggering though. 
I am only pretty sure that AR0231-AP02X-GMSL2 camera has triggering feature enabled.
