### ISSUE TITLE
Read sensor register sometimes get incorrect value 0xa80e

### ISSUE THREAD

**Issue by xiao6768** [danyu9394/linux_camera_tool#5]
Press read resister quickly, it will print 0xa80e.
by monitor low level I2C signal, found device report NACK when issue command I2C read, but MCU does not handle , and continue read out, then unexpected value output.

**Comment by xiao6768** [comment]
Here is my email address: hchen@nullmax.ai    please mail me ,I will send you the screen shot and capture data by saleae16. thanks.

**Comment by danyu9394** [comment]
Hi,

if you get NACK for I2C. Mostly likely you weren't read the correct I2C slave addr, or that camera generic I2C reed/write interface hasn't been enabled.
Can you tell me which camera you are using and the firmare rev?

**Comment by xiao6768** [comment]
Hi ,
Appreciate of your prompt reply.
My camera type is Ar0231, FW version is 0.
I don't think it is slave address issue. because :
1. doing continuously read by enable 'just sensor read/write'
2. correct value and incorrect value are output alternately.

From my opinion, it might related to the firmware running in CYUSB3014. 
thanks.

**Comment by danyu9394** [comment]
Hi,

are you using AR0231 GMSL1 USB3 or a simple AR0231 tester USB3 board? 
There is a new firmware that fix instability issue for [AR0231 GMSL1 USB3]. Please refer to #4 
From your description, it seems that somewhere in the firmware, it is writing to the interface not to read from sensor but probably another i2c slave on the bus...

**Comment by xiao6768** [comment]
Hi,
I think I am using the AR0231 tester USB3 board.
there is mark on it "LI-USB3.0 V1.6"
![image](https://user-images.githubusercontent.com/22783754/60569091-0fb00480-9da1-11e9-9423-85f9b7515fe2.png)

**Comment by danyu9394** [comment]
Hi,

it looks like a AR0231 GMSL1 USB3 camera since I see a coax cable >.<
Can you try to read the register value from sensor slave address (0x30/0x20) and see if there has NAK in I2C? You are right about it is not linux camera tool API's fault but firmware's. (We have many old firmwares that didn't add both I2C R/W interfaces or only one of them for many reasons... Your weird read back value is an example.) 
I will send you a firmware update once I confirm which camera you have.

**Comment by xiao6768** [comment]
Hi Danyu,
Read sensor with slave address 0x20/0x30,there is no luck.
here is my camera model, please share new firmware.
(BTW, does the firmware code open source? it would be great if it's open source.)
![image](https://user-images.githubusercontent.com/22783754/60637940-05e4da80-9e4f-11e9-9858-bf0b5be602b6.png)
![image](https://user-images.githubusercontent.com/22783754/60637950-0d0be880-9e4f-11e9-88d3-7d987393bd2e.png)

**Comment by danyu9394** [comment]
Hi,

attach the firmware update for AR0231 GMSL1 USB3 correcting sensor & generic i2c register access functions. You can use "li_firmware_updates" tool inside this project folder for firmware update. 
I've tested the camera. You should be able to talk to sensor through both interfaces by now. 8-bit I2C slave addr for sensor is 0x20. Let me know if you still have questions.
[https://www.dropbox.com/s/tnm1cd4f2zrufqg/cyfxuvc_rev1454.lif?dl=0]
Unluckily, our USB3 firmware is not open-source. This project is quite old and is not putting in USB3 trunk. So most of the new added (or even some normal) extension unit ctrls are not available... I hope you will be finding these features enough for now :D Let me know if you have any more questions.

**Comment by xiao6768** [comment]
Hi,
By upgrade FW , problem has been resolved perfectly!
thanks for all your help.
My last question is 'auto exposre' does not work. check or uncheck the display has no change.
Is this controlled by cypress chip also?

**Comment by danyu9394** [comment]
Hi,

this sensor(AR0231) doesn't have AE support. So even it has this interface exposed, it actually isn't doing anything in FX3 to send command to sensor.

**Comment by xiao6768** [comment]
Hi Danyu,
Okay, 
Appreciate of your strong support! wish you a good day!
