### ISSUE TITLE
More than one instance

### ISSUE THREAD

**Issue by PinkSnake** [danyu9394/linux_camera_tool#7]
Hi,

First thx for your work ;)

Do you think it will be possible to run one more instance of your code ? Because I have tried with 2 OV2311 cam but i have VIDIOC_DQBUF issue ( note in read me doesn't help :s)

Cheers

**Comment by xiao6768** [comment]
Hi there,
from my understanding, (Learn from source code) the mmap share variable make it is unable to support multiple instance.

**Comment by PinkSnake** [comment]
Hi,

Do you know if there a lot of work to fix that ? I didn't take a deep look into the code yet.

**Comment by danyu9394** [comment]
Hi,

so far my code doesn't support multiple leopard USB3 cameras. There is a bug in udev that kinda messes up with my physical video devices, I haven't been able to solve :( Any help will be appreciated!
If you get VIDIOC_DQBUF error message, most likely your previous **leopard_cam** application hasn't been entirely closed(in zombie process), you can use `ps` to see existing process, and use`killall -9 leopard_cam` to kill the last zoombie process. And then run leopard_cam again.

**Comment by danyu9394** [comment]
Hi,
I updated the code so that you can run multiple different LI USB3 cameras now. You will need a firmware update for different product id so your host PC is not confused with same cameras to be able to run multiple of our cameras.

**Comment by PinkSnake** [comment]
Thanks a lot! :)
