### ISSUE TITLE
VID not found 

### ISSUE THREAD

**Issue by SnailWalkerYC** [danyu9394/linux_camera_tool#8]
Hi I have installed the driver, but when I run the leopard_cam, it will show the following messages:
open video device fail: No such file or directory
open camera /dev/video0 failed,err code:-1

Wha should I do to fix this problem? And I use lsusb and not found the usual VID

**Comment by danyu9394** [comment]
Hi, it seems your PC hasn't detected any video device. 
1. Try to connect your camera with a USB3 hub or another USB3 port. 
2. Do `lsusb` or `ls /dev/vi*` make sure your PC detect the camera first then you should be able to use this software

**Comment by SnailWalkerYC** [comment]
> Hi, it seems your PC hasn't detected any video device.
> 
> 1. Try to connect your camera with a USB3 hub or another USB3 port.
> 2. Do `lsusb` or `ls /dev/vi*` make sure your PC detect the camera first then you should be able to use this software

Thank you. It's the device problem.
